Make spotlight effect more accurate and use builtin
dhs-gamedev/flowerknight pull request #36
Opened 2021-06-02 04:54 UTC by adamhutchings

2021-06-02 06:47 UTC, Camerooooon approved these changes
Works

2021-06-02 07:18 UTC, JakeRoggenbuck requested changes
It looks smooth but it's very bright

2021-06-03 06:38 UTC, JakeRoggenbuck approved these changes

2021-06-04 21:33 UTC, Shuzhengz approved these changes
Да

2021-06-04 21:44 UTC, merged